postgresURI = "<YOUR POSTGRES DATABASE URI>"

mongouser = "<YOUR MONGO ATLAS USER>"
mongopass = "<YOUR MONGO ATLAS USER's PASSWORD>"

# reddit api
clientID = "<YOUR REDDIT APP CLIENT ID>"
clientSecret = "<YOUR REDDIT APP CLIENT SECRET>"
